apiVersion: batch/v1
kind: Job
metadata:
  name: give-your-job-a-name:
  namespace: gp-engine-mizzou-mindful
spec:
  template:
    metadata:
      name: pytorch-training-pod
    spec:
      restartPolicy: Never
      containers:
      - name: pytorch-container--1
        image: gitlab-registry.nrp-nautilus.io/jdapm8/docker-pytorch-example:latest
        command: ["/bin/bash", "-c"]
        # this "args" param is where the start command goes
        args: ["nvidia-smi && cd /workspace/models && pwd && ls && python3 ./pytorch_example.py"]
        volumeMounts:
        - name: output_private_volume
          mountPath: /root/host_fs
        resources:
            requests:
              memory: "4Gi"
              cpu: "2"
              nvidia.com/gpu: "1"
            limits:
              memory: "16Gi"
              cpu: "4"
              nvidia.com/gpu: "1"
      volumes:
      - name: output_private_volume
        persistentVolumeClaim:
          claimName: name-of-your-private-volume:
