apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: name-this-something-unique:
  namespace: gp-engine-mizzou-mindful
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
