apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["sleep", "3600"]  # Keeps the Pod running for an hour
    volumeMounts:
    - name: my-pv
      mountPath: /mnt
  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: name-of-your-private-volume:
